### ISSUE TITLE
Usar seu fonte/UI numa apresentação

### ISSUE THREAD

**Issue by carolzbnbr** [ErickSilva2605/xamarinforms-nft-wallet#1]
Ola Erick, tudo bem?

Primeiramente adorei sua UI.

Diz uma coisa, em breve, talvez, eu vá fazer uma apresentação sobre MAUI e irei falar sobre minha [Markup extension](https://github.com/carolzbnbr/OnScreenSizeMarkup) que em breve subirá pro Maui Community Toolkit.

Como seu layout é bem colorido e bonito, pensei que talvez pudesse usar na minha apresentação (irei converter pra MAUI), pra demonstrar o funcionamento da minha markup extension no seu app.

Voce me permitiria o uso do seu fonte nessa apresentação? 

Obviamente, caso você aprove, eu faria a menção do endereço do github do fonte-original de onde peguei o código.

Fico no aguardo e desde já agradeço.

Carol

**Comment by ErickSilva2605** [comment]
Olá Carol, tudo bem sim e com você ?

Muito obrigado pelo elogio e fico feliz que tenha gostado!

Seria um prazer poder contribuir de alguma forma com seu trabalho, ainda mais com algo da comunidade. Pode usar sem problema a UI e no que precisar estou a disposição!

E caso sua apresentação seja aberta ao publico e online, ficaria feliz em poder assistir. Te desejo boa sorte e agradeço pelo contato!

**Comment by carolzbnbr** [comment]
Ainda está tudo bem no começo, mas se acontecer msm esse evento será no Microsoft Reactor em SP, mas ainda não sei se será transmitido ao vivo, grandes chances de ser. Se for ao vivo e aberto, te passo o link sim. 

Obrigada por disponibilizar seu fonte pra demo. Na vdd como terei de migrar pra maui, estou também considerando um design que eu tenho já há algum tempo, vamos ver. 

De qualquer forma te aviso. 

Super Obrigada Erick!! 

Carol
